apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-apps
  namespace: jenkins 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: Jenkins-role
subjects:
- kind: User
  name: system:serviceaccount:jenkins:ec-service-account
  apiGroup: rbac.authorization.k8s.io

